### ISSUE TITLE
Avoid pinned version of chrono

### ISSUE THREAD

**Issue by sunng87** [gluesql/gluesql#1227]
We are using pinned version of chrono in core (chrono "=0.4.23"). This leads to dependency conflicts in projects that has both `chrono 0.4.24` and gluesql included. From the commit history it seems we don't have a particular requirement for chrono 0.4.23, so it will be nice to have chrono version like "0.4.23", which mean any "0.4" patch releases above "23"

**Comment by ever0de** [comment]
I don't remember the exact context, but I think there was something that broke semver during the patch version bump, so I fixed it. (I didn't upload the lock file at the time, so the builds of people who received the new clone were broken.)
Now I can put it back up as a minor version.

**Comment by mjm918** [comment]
Hi is there any fix for this issue? I have libraries running different version of chrono in my project.

**Comment by panarch** [comment]
Oh thanks for the reminder. I just made fix for this.
You can expect to use it if you use the main branch, or we may release GlueSQL@v0.15 in a few weeks so you will be able to use the released version soon.

**Comment by rolandjitsu** [comment]
I'm still having issues on v0.16:
```
error: failed to select a version for `chrono`.
    ... required by package `duration-str v0.11.0`
    ... which satisfies dependency `duration-str = "^0.11"` of package `data_store v0.1.0 (/Users/rolandgroza/Work/jungle/data_store)`
versions that meet the requirements `^0.4.38` are: 0.4.38

all possible versions conflict with previously selected packages.

  previously selected package `chrono v0.4.33`
    ... which satisfies dependency `chrono = "=0.4.33"` of package `gluesql-core v0.16.0`
    ... which satisfies dependency `gluesql-core = "^0.16.0"` of package `gluesql v0.16.0`
    ... which satisfies dependency `gluesql = "^0.16.0"` of package `data_store v0.1.0 (/Users/rolandgroza/Work/jungle/data_store)`

failed to select a version for `chrono` which could resolve this conflict

```

I'm using [duration-str](https://github.com/baoyachi/duration-str) which depends on:
```
chrono = { version = "0.4.38", optional = true, default-features = false, features = ["now"] }
```

**Comment by panarch** [comment]
@rolandjitsu soon to be fixed and then I will release 0.16.2.
ref. https://github.com/gluesql/gluesql/pull/1565

**Comment by rolandjitsu** [comment]
Thanks @panarch for the update. I'll keep an eye out for the release.

**Comment by panarch** [comment]
@rolandjitsu I've released 0.16.2 yesterday. now you can use it :D
